### ISSUE TITLE
dynamic libraries not enabled check your lua installation

### ISSUE THREAD

**Issue by imolein** [akornatskyy/docker-library#1]
Hi,

I used your luarocks-lua5.3 image and run into a problem when using luafilesystem. I created the following Dockerfile:

```
FROM akorn/luarocks:lua5.3-alpine

RUN set -ex \
    && apk add --no-cache \
        ca-certificates \
        openssl \
        curl \
        git \
    && apk add --no-cache --virtual .build-deps \
        make \
        gcc \
        libc-dev \
        build-base \
        autoconf \
        openssl-dev \
        bsd-compat-headers \
    && luarocks install luafilesystem

CMD ["lua"]
```

and when run it and try to load lfs, I get the following:
```
root@docker-test ~/test # docker run -it --rm cd9142cc15de
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> lfs = require('lfs')
error loading module 'lfs' from file '/usr/local/lib/lua/5.3/lfs.so':
	dynamic libraries not enabled; check your Lua installation
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: in ?
> 
```

I changed your lua5.3 image then and build lua with platform linux, instead of posix and then I could load lfs. It would be nice if you can change this or is there a reason why you use posix instead of linux?

greetings Sebastian

**Comment by alerque** [comment]
Same issue here. I see there is other recent activity on this repo. Is there a chance of getting this fixed or should I look into building my own images or what? It seems objectively wrong to have the build setup this way and quite restrictive on what downstream Lua stuff stands a chance of running in these containers.

**Comment by imolein** [comment]
> or should I look into building my own images or what

Because I got no reaction (which is a pity but totally ok for me) I did exactly this :)

**Comment by akornatskyy** [comment]
@alerque : do you experience an issue with `lfs`? what is your particular case?

**Comment by alerque** [comment]
@akornatskyy Yes I initially ran into this with LuaFileSystem in specific. My particular use case is I am working on getting a new Busted release out the door and wanted to add a containerized version so the official upstream Busted repository could be used as a GitHub Action. The issue starts with LFS which is a Busted dependency, but it doesn't stop there. Because projects would need to customize what modules are available I needed an image with LuaRocks on it along with whatever dependencies were needed to build a wide variety of dependencies.

Lua being compiled with a target of `posix` instead of `linux` seems to be a blocker. It may be that there are other issues with trying to do this on Alpine and I should be looking into something bigger like an Arch Linux base image, but I wanted to try to start small.

**Comment by akornatskyy** [comment]
it targets `linux` now... it required to add `readline` as runtime dependency, more [here](https://github.com/akornatskyy/docker-library/commit/72e18456797a20d9155d40ccf8e9bdd19ef48120). the images have been updated.

**Comment by akornatskyy** [comment]
to use `lfs` you need install `gcc` and `libc-dev`, since they are compile dependencies for `luafilesystem`.
```sh
apk add gcc libc-dev
luarocks install luafilesystem
lua -l lfs
```

**Comment by Aire-One** [comment]
What are the odds? I just stepped on the same problem!

I can confirm that after updating the docker image, and adding the `apk add gcc libc-dev` to my CI pipeline, it now works as expected.

Thank you for your work @akornatskyy

**Comment by alerque** [comment]
Thanks a lot! I'll take another stab at using this.

I think the LuaRocks images need rebuilding though. The images on Docker Hub start out based on the plain Lua images. I see there are rebuilds of the plain images but the other ones are a couple weeks old.

Also looking at the Dockerfile's I'm a bit confuused on why `gcc` `libc-dev` would be needed since they are installed in the image already. Perhaps that is more a function of using an out of date image?

**Comment by akornatskyy** [comment]
well... the luarocks images where rebuilt and published, docker hub says 6 hours ago. so that might be something different at your side.

regarding `gcc` and `libc-dev`, these were added in image just to build `lua`, they are removed since are not necessary as a runtime dependency. [here](https://github.com/akornatskyy/docker-library/blob/master/lua/5.4/alpine/Dockerfile#L35) is the line that removes compile time dependencies.

**Comment by alerque** [comment]
Hmm, thanks again for the explanations. I did miss how the dependencies were being removed.

Also Docker Hub has updated for me too (after several refreshes).

**Comment by alerque** [comment]
I have testing this and everything is working as expected. As far as I can see this issue can be closed!

Expect to see these used as the base images for the GH Action flavor in next release of Luacheck as well as Busted.
